In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Bollywood Dataset

In [2]:
df = pd.read_csv("movieData.csv")
df

,Title,Image Link,Year,IMDb Rating,Review,Runtime,Genre,Certificate
0,The Night Manager,https://m.media-amazon.com/images/M/MV5BYjU2ND...,2023.0,7.7,"Follows Shaan Sengupta, an ex-soldier, who mus...",47 min,"Action, Crime, Mystery",A
1,The Jengaburu Curse,https://m.media-amazon.com/images/M/MV5BNDU0Y2...,2023.0,8.0,A London-based analyst returns to Odisha in se...,NaN,Thriller,A
2,Bro,https://m.media-amazon.com/images/M/MV5BN2M2ZT...,2023.0,7.9,An arrogant man is given a second chance to fi...,134 min,"Drama, Family, Fantasy",U
3,Farzi,https://m.media-amazon.com/images/M/MV5BNThlNG...,2023.0,8.4,An artist who gets pulled into the murky high ...,56 min,"Crime, Drama, Thriller",A
4,Crackdown,https://m.media-amazon.com/images/M/MV5BNzQ4Nz...,2020.0,8.1,A high intensity action-thriller Crackdown 2 s...,30 min,"Action, Crime, Drama",16
...,...,...,...,...,...,...,...,...
49945,Thattathin Marayathu,https://m.media-amazon.com/images/M/MV5BMGJkYT...,2012.0,7.5,The struggles faced when a Hindu man falls in ...,127 min,"Drama, Romance",U
49946,Nishpaap,https://m.media-amazon.com/images/M/MV5BZWVlNT...,1992.0,NaN,Satish Gaikwad is in love with school going As...,NaN,Drama,NaN
49947,Akhada,https://m.media-amazon.com/images/M/MV5BNzgxMz...,2022.0,8.7,A Young ambitious wrestler Karan falls prey to...,NaN,"Drama, Sport",Not Rated
49948,Haseena,https://m.media-amazon.com/images/M/MV5BZTcyZD...,2018.0,4.3,"Three boys swooned by the beauty of Haseena, w...",135 min,Comedy,A
49949,Hero of Nation Chandra Shekhar Azad,https://m.media-amazon.com/images/M/MV5BYTI1MD...,2022.0,9.2,Chandrashekhar Azad has been a leader in the f...,NaN,Biography,NaN

In [3]:
df = df[['Title','Review','Genre']]
df

,Title,Review,Genre
0,The Night Manager,"Follows Shaan Sengupta, an ex-soldier, who mus...","Action, Crime, Mystery"
1,The Jengaburu Curse,A London-based analyst returns to Odisha in se...,Thriller
2,Bro,An arrogant man is given a second chance to fi...,"Drama, Family, Fantasy"
3,Farzi,An artist who gets pulled into the murky high ...,"Crime, Drama, Thriller"
4,Crackdown,A high intensity action-thriller Crackdown 2 s...,"Action, Crime, Drama"
...,...,...,...
49945,Thattathin Marayathu,The struggles faced when a Hindu man falls in ...,"Drama, Romance"
49946,Nishpaap,Satish Gaikwad is in love with school going As...,Drama
49947,Akhada,A Young ambitious wrestler Karan falls prey to...,"Drama, Sport"
49948,Haseena,"Three boys swooned by the beauty of Haseena, w...",Comedy
49949,Hero of Nation Chandra Shekhar Azad,Chandrashekhar Azad has been a leader in the f...,Biography

In [4]:
df.shape

(49950, 3)

In [5]:
len(df['Title'].unique())

1134

In [6]:
features = df.columns.to_list()
for i in features:
    print(df[i].isna().sum())

0
0
628

In [16]:
df['Genre'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
49945    False
49946    False
49947    False
49948    False
49949    False
Name: Genre, Length: 49950, dtype: bool

In [7]:
df = df.drop_duplicates(subset=['Title'])

In [8]:
df

,Title,Review,Genre
0,The Night Manager,"Follows Shaan Sengupta, an ex-soldier, who mus...","Action, Crime, Mystery"
1,The Jengaburu Curse,A London-based analyst returns to Odisha in se...,Thriller
2,Bro,An arrogant man is given a second chance to fi...,"Drama, Family, Fantasy"
3,Farzi,An artist who gets pulled into the murky high ...,"Crime, Drama, Thriller"
4,Crackdown,A high intensity action-thriller Crackdown 2 s...,"Action, Crime, Drama"
...,...,...,...
49749,Thattathin Marayathu,The struggles faced when a Hindu man falls in ...,"Drama, Romance"
49799,Nishpaap,Satish Gaikwad is in love with school going As...,Drama
49849,Akhada,A Young ambitious wrestler Karan falls prey to...,"Drama, Sport"
49899,Haseena,"Three boys swooned by the beauty of Haseena, w...",Comedy
49949,Hero of Nation Chandra Shekhar Azad,Chandrashekhar Azad has been a leader in the f...,Biography

In [12]:
df['Review'] = df['Review'].str.replace('See full summary', '', regex=False).str.strip()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22696\2958757539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Review'] = df['Review'].str.replace('See full summary', '', regex=False).str.strip()

In [15]:
df.rename(columns={"Title":"title","Review":"desc","Genre":"genre"},inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22696\1752397478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"Title":"title","Review":"desc","Genre":"genre"},inplace=True)

In [16]:
df

,title,desc,genre
0,The Night Manager,"Follows Shaan Sengupta, an ex-soldier, who mus...","Action, Crime, Mystery"
1,The Jengaburu Curse,A London-based analyst returns to Odisha in se...,Thriller
2,Bro,An arrogant man is given a second chance to fi...,"Drama, Family, Fantasy"
3,Farzi,An artist who gets pulled into the murky high ...,"Crime, Drama, Thriller"
4,Crackdown,A high intensity action-thriller Crackdown 2 s...,"Action, Crime, Drama"
...,...,...,...
49749,Thattathin Marayathu,The struggles faced when a Hindu man falls in ...,"Drama, Romance"
49799,Nishpaap,Satish Gaikwad is in love with school going As...,Drama
49849,Akhada,A Young ambitious wrestler Karan falls prey to...,"Drama, Sport"
49899,Haseena,"Three boys swooned by the beauty of Haseena, w...",Comedy
49949,Hero of Nation Chandra Shekhar Azad,Chandrashekhar Azad has been a leader in the f...,Biography

In [35]:
df.to_csv('Datasets/bollywood.csv',index=False)

#### HollyWood Dataset

In [18]:
holywood = pd.read_csv('tmdbHollywood.csv')
holywood

,Unnamed: 0,title,overview,original_language,vote_count,vote_average
0,0,Ad Astra,"The near future, a time when both hope and har...",en,2853,5.9
1,1,Bloodshot,"After he and his wife are murdered, marine Ray...",en,1349,7.2
2,2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2530,7.1
3,3,Ant-Man,Armed with the astonishing ability to shrink i...,en,13611,7.1
4,4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",en,3542,5.9
...,...,...,...,...,...,...
9995,9995,Cargo,The story of CARGO takes place on rusty space-...,de,225,5.9
9996,9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...",en,67,5.6
9997,9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...",fr,234,7.1
9998,9998,The Grand Seduction,A small fishing village must procure a local d...,en,169,6.7
9999,9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...",ko,78,6.7

In [20]:
holywood = pd.read_csv('hollywood_movies_with_genres.csv')
holywood['genre'].isna().sum()

np.int64(3922)

In [21]:
len(holywood['title'].unique())

9689

In [22]:
len(holywood)

10000

In [26]:
holywood = holywood.drop_duplicates(subset=['title'])
len(holywood)

9689

In [27]:
holywood.rename(columns={"overview":"desc"},inplace=True)

In [28]:
holywood

,Unnamed: 0,title,desc,original_language,vote_count,vote_average,genre
0,0,Ad Astra,"The near future, a time when both hope and har...",en,2853,5.9,"Science Fiction, Drama"
1,1,Bloodshot,"After he and his wife are murdered, marine Ray...",en,1349,7.2,"Action, Science Fiction, Adventure"
2,2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2530,7.1,"Thriller, Action, Crime"
3,3,Ant-Man,Armed with the astonishing ability to shrink i...,en,13611,7.1,"Science Fiction, Adventure, Action"
4,4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",en,3542,5.9,"Adventure, Family, Fantasy"
...,...,...,...,...,...,...,...
9994,9994,Zapped!,Peyton and Barney are fun loving high school s...,en,64,5.2,"TV Movie, Comedy, Family"
9996,9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...",en,67,5.6,"Comedy, Drama, Romance, Fantasy, Music"
9997,9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...",fr,234,7.1,"Comedy, Crime"
9998,9998,The Grand Seduction,A small fishing village must procure a local d...,en,169,6.7,Comedy
9999,9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...",ko,78,6.7,"Adventure, Action, Comedy, Fantasy"

In [30]:
holywood = holywood[['title','desc','genre']]
holywood

,title,desc,genre
0,Ad Astra,"The near future, a time when both hope and har...","Science Fiction, Drama"
1,Bloodshot,"After he and his wife are murdered, marine Ray...","Action, Science Fiction, Adventure"
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,"Thriller, Action, Crime"
3,Ant-Man,Armed with the astonishing ability to shrink i...,"Science Fiction, Adventure, Action"
4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...","Adventure, Family, Fantasy"
...,...,...,...
9994,Zapped!,Peyton and Barney are fun loving high school s...,"TV Movie, Comedy, Family"
9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...","Comedy, Drama, Romance, Fantasy, Music"
9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...","Comedy, Crime"
9998,The Grand Seduction,A small fishing village must procure a local d...,Comedy
9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...","Adventure, Action, Comedy, Fantasy"

In [34]:
holywood.to_csv('Datasets/hollywood.csv',index=False)