In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Datasets/bollywood.csv")
df

,title,desc,genre
0,The Night Manager,"Follows Shaan Sengupta, an ex-soldier, who mus...","Action, Crime, Mystery"
1,The Jengaburu Curse,A London-based analyst returns to Odisha in se...,Thriller
2,Bro,An arrogant man is given a second chance to fi...,"Drama, Family, Fantasy"
3,Farzi,An artist who gets pulled into the murky high ...,"Crime, Drama, Thriller"
4,Crackdown,A high intensity action-thriller Crackdown 2 s...,"Action, Crime, Drama"
...,...,...,...
1129,Thattathin Marayathu,The struggles faced when a Hindu man falls in ...,"Drama, Romance"
1130,Nishpaap,Satish Gaikwad is in love with school going As...,Drama
1131,Akhada,A Young ambitious wrestler Karan falls prey to...,"Drama, Sport"
1132,Haseena,"Three boys swooned by the beauty of Haseena, w...",Comedy
1133,Hero of Nation Chandra Shekhar Azad,Chandrashekhar Azad has been a leader in the f...,Biography

In [4]:
# df = df.dropna()
df.shape

(1134, 3)

In [5]:
features = df.columns.to_list()
print(features)

['title', 'desc', 'genre']

In [6]:
titleFeature = df['title']
descFeature = df['desc']
genreFeature = df['genre'].str.replace(","," ")
# genreFeature
descFeature

0       Follows Shaan Sengupta, an ex-soldier, who mus...
1       A London-based analyst returns to Odisha in se...
2       An arrogant man is given a second chance to fi...
3       An artist who gets pulled into the murky high ...
4       A high intensity action-thriller Crackdown 2 s...
                              ...
1129    The struggles faced when a Hindu man falls in ...
1130    Satish Gaikwad is in love with school going As...
1131    A Young ambitious wrestler Karan falls prey to...
1132    Three boys swooned by the beauty of Haseena, w...
1133    Chandrashekhar Azad has been a leader in the f...
Name: desc, Length: 1134, dtype: object

In [10]:
# uniqueFeatures = ['genre']
# genre = []
# for i in uniqueFeatures:
#     if i=='genre':
#         genre = df[i].unique()
#     print(i)
#     print(df[i].unique())
#     print("\n")

genre
['Action, Crime, Mystery' 'Thriller' 'Drama, Family, Fantasy'
 'Crime, Drama, Thriller' 'Action, Crime, Drama' 'Action, Thriller'
 'Drama' 'Comedy, Drama' 'Crime, Drama, Mystery' 'Comedy, Drama, Musical'
 'Action, Drama, Romance' 'Action, Adventure, Drama' 'Mystery'
 'Action, Comedy' 'Action, Crime, Thriller' 'Action, Comedy, Drama'
 'Comedy, Drama, Fantasy' 'Action, Drama, Thriller' 'Drama, Romance' nan
 'Comedy, Crime, Drama' 'Biography, Crime, Drama'
 'Action, Adventure, Thriller' 'Comedy, Romance'
 'Action, Biography, Drama' 'Action, Drama' 'Drama, History'
 'Adventure, Drama, Sci-Fi' 'Drama, Fantasy, Horror'
 'Action, Adventure, Fantasy' 'Drama, Family' 'Action, Biography, Crime'
 'Comedy, Crime, Romance' 'Comedy, Drama, Romance'
 'Action, Drama, Fantasy' 'Crime, Drama' 'Drama, Thriller'
 'Action, Comedy, Crime' 'Action, Drama, Mystery' 'Comedy, Drama, Family'
 'Drama, Musical' 'Drama, Musical, Sport' 'Action, Adventure, Comedy'
 'Crime, Mystery, Thriller' 'Crime, Horror, Mystery'
 'Action, Drama, History' 'Documentary, Biography, News'
 'Drama, Mystery, Romance' 'Drama, Music, Romance' 'Comedy'
 'Comedy, Drama, Thriller' 'Adventure, Drama, Romance'
 'Drama, Musical, Romance' 'Comedy, Horror' 'Adventure, Comedy, Drama'
 'Documentary, Short' 'Drama, Sport' 'Crime, Drama, Romance'
 'Crime, Drama, History' 'Drama, Music, Musical'
 'Action, Adventure, Crime' 'Comedy, Crime, Mystery'
 'Drama, History, Romance' 'Action, Comedy, Thriller'
 'Drama, Mystery, Thriller' 'Crime, Thriller' 'War' 'Comedy, Fantasy'
 'Crime' 'Action' 'Drama, Family, Sport' 'Crime, Drama, Horror'
 'Action, Sci-Fi, Thriller' 'Biography, Drama, History'
 'Documentary, Crime, History' 'Drama, Horror, Musical'
 'Action, Drama, Sport' 'Family' 'Horror' 'Adventure, Drama'
 'Biography, Drama' 'Comedy, Mystery, Thriller' 'Horror, Thriller'
 'Action, Drama, Musical' 'Fantasy, Horror, Sci-Fi'
 'Horror, Mystery, Thriller' 'Action, Comedy, Fantasy' 'Fantasy'
 'Drama, Music' 'Action, Drama, War' 'Sport' 'Comedy, Drama, Mystery'
 'Action, Crime, Romance' 'Adventure, Crime, Mystery'
 'Action, Drama, Sci-Fi' 'Drama, Fantasy' 'Animation, Comedy'
 'Drama, Romance, Thriller' 'Romance' 'Drama, Family, Romance'
 'Action, Crime' 'Adventure, Reality-TV' 'Drama, Horror, Romance'
 'Romance, Thriller' 'Animation, Comedy, Family' 'Mystery, Thriller'
 'Horror, Mystery, Romance' 'Short, Drama, Romance' 'Documentary'
 'Comedy, Romance, Sci-Fi' 'Reality-TV' 'Action, Thriller, War' 'Short'
 'Action, Adventure' 'Comedy, Horror, Mystery' 'Drama, Mystery'
 'Biography, Drama, Sport' 'Musical, Mystery, Thriller'
 'Biography, History, War' 'Comedy, Family' 'Crime, Drama, Music'
 'Comedy, Romance, Thriller' 'Action, Comedy, Family'
 'Biography, History, Mystery' 'Adventure, Drama, Thriller'
 'Comedy, Drama, History' 'Comedy, Fantasy, Horror'
 'Comedy, Crime, Thriller' 'Crime, Romance, Thriller'
 'Adventure, Comedy, Horror' 'Biography' 'Mystery, Romance, Thriller'
 'Comedy, Drama, Horror' 'Documentary, Crime, Mystery'
 'Drama, Fantasy, Romance' 'Action, Comedy, Romance'
 'Action, Horror, Sci-Fi' 'Comedy, Drama, Sci-Fi'
 'Comedy, Sci-Fi, Thriller' 'Short, Thriller' 'Action, Musical, Romance'
 'History, War' 'History, Thriller' 'Adventure, Comedy, Mystery'
 'Drama, Romance, War' 'Action, Fantasy' 'Animation, Action, Adventure'
 'Short, Comedy, Romance' 'Action, Musical, Mystery'
 'Drama, Horror, Thriller' 'Drama, Fantasy, Mystery' 'Comedy, Thriller'
 'Biography, Comedy, Drama' 'Reality-TV, Talk-Show'
 'Action, Comedy, Horror' 'History' 'Comedy, Talk-Show'
 'Animation, Horror' 'Comedy, Fantasy, Romance' 'Biography, History'
 'Adventure, Drama, Fantasy' 'Adventure, Comedy, Crime' 'Animation, Drama'
 'Drama, Thriller, Action' 'Music, Reality-TV' 'Comedy, Musical, Romance'
 'Action, Romance' 'Action, Family, Thriller' 'Family, Musical, Romance'
 'Short, Comedy' 'Action, Drama, Family' 'Documentary, Sport'
 'Drama, Family, Musical' 'Music, Romance' 'Action, Adventure, Family'
 'Drama, Horror' 'Musical, Drama, Romance' 'Animation']

#### Genre based Only

In [ ]:
# # genre = genre.tolist()
# # print(genre)
# uniqueGenre = set()
# for i in genre:
#     Glist = i.split(",")
#     for j in Glist:
#         if j[0]==" " or j[len(j)-1]==" ":
#             removeSpace = j.split(" ")
#             for u in removeSpace:
#                 if u!=" ":
#                     uniqueGenre.add(u)
#         else:
#             uniqueGenre.add(j)
# print(uniqueGenre)
# print(len(uniqueGenre))

In [9]:
# k = " Drama            "
# k= "Family            "
# if j[0]==" " or j[len(j)-1]==" ":
#         removeSpace = k.split(" ")
#         for u in removeSpace:
#             if u!=" ":
#                   uniqueGenre.add(j)
#         print(removeSpace)

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# vectorizer = CountVectorizer()

# vec = vectorizer.fit_transform(genreFeature)
# print(vectorizer.get_feature_names_out())

# search = "drama thriller"
# srchVec = vectorizer.transform([search])

# # print(vec.toarray())

In [ ]:
# from sklearn.metrics.pairwise import cosine_similarity

# similar = cosine_similarity(srchVec,vec).flatten()
# print(similar)

# topK = 5
# topIndex = np.argsort(similar)[::-1][:topK]
# print(topIndex)

[0.81649658 0.         0.40824829 ... 0.70710678 0.         0.        ]
[ 419   22 1433 3098 3112]

In [ ]:
# for i in topIndex:
#     print(df['title'].iloc[i])
#     print("Cosine Value: ", similar[i])
#     print("\n")

Trapped
Cosine Value:  0.9999999999999998


Blurr
Cosine Value:  0.9999999999999998


Malayankunju
Cosine Value:  0.9999999999999998


Meppadiyan
Cosine Value:  0.9999999999999998


Maalgudi Days
Cosine Value:  0.9999999999999998

#### Desc & Genre (Bollywood)

In [9]:
descGenreFeature = genreFeature.fillna("") + descFeature.fillna("")
descGenreFeature

0       Action  Crime  MysteryFollows Shaan Sengupta, ...
1       ThrillerA London-based analyst returns to Odis...
2       Drama  Family  FantasyAn arrogant man is given...
3       Crime  Drama  ThrillerAn artist who gets pulle...
4       Action  Crime  DramaA high intensity action-th...
                              ...
1129    Drama  RomanceThe struggles faced when a Hindu...
1130    DramaSatish Gaikwad is in love with school goi...
1131    Drama  SportA Young ambitious wrestler Karan f...
1132    ComedyThree boys swooned by the beauty of Hase...
1133    BiographyChandrashekhar Azad has been a leader...
Length: 1134, dtype: object

In [8]:
print(len(descGenreFeature))
print(len(df))

1134
1134

In [10]:
# vectorizer = CountVectorizer()
# vectorizer = CountVectorizer(stop_words="english")
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words="english")

decvec = vectorizer.fit_transform(descGenreFeature)
print(vectorizer.get_feature_names_out())

# searchDec = "Action based new cool fiction story"
# searchDec = "horror"
# searchDec = df["desc"].iloc[100]
searchDec = "serial killer murder investigation"

srchDecVec = vectorizer.transform([searchDec])

# print(vec.toarray())

['000' '10' '100' ... 'zombies' 'zoo' 'zuberi']

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

similarDec = cosine_similarity(srchDecVec,decvec).flatten()
print(similarDec)

topK = 5
topIndexDec = np.argsort(similarDec)[::-1][:topK]
print(topIndexDec)

[0. 0. 0. ... 0. 0. 0.]
[ 220   21  143   90 1118]

In [14]:
print("Search keyword: ",searchDec)
print("\n")
for i in topIndexDec:
    print(df['title'].iloc[i])
    print("Cosine Value: ", similarDec[i])
    print(df['desc'].iloc[i])
    print("\n")

Search keyword:  serial killer murder investigation


Anjaam Pathiraa
Cosine Value:  0.3571200704122786
The police are on the trail of a serial killer, but with the victims being fellow officers, will they be able to catch the killer and solve the case in time?


Dahaad
Cosine Value:  0.2630631769375753
Sub-inspector Anjali Bhaati investigates a series of deaths where women are found in public bathrooms. The deaths first appear as suicides but as the investigation progresses, Bhaati realizes that there's a serial killer on the loose.


Operation Mayfair
Cosine Value:  0.25077743342296815
A detective hunts for a London-based serial killer who targets women in this gritty Hindi language thriller.


Ratsasan
Cosine Value:  0.24699551708525908
A sub-inspector sets out in pursuit of a mysterious serial killer who targets teen school girls and murders them brutally.


Bichhoo
Cosine Value:  0.24415325248937494
A contract killer with a tragic past trains a teenage girl to avenge the murder of her family and falls for her in the process.

#### Desc & Genre (Hollywood)

In [15]:
hdf = pd.read_csv("Datasets/hollywood.csv")
hdf

,title,desc,genre
0,Ad Astra,"The near future, a time when both hope and har...","Science Fiction, Drama"
1,Bloodshot,"After he and his wife are murdered, marine Ray...","Action, Science Fiction, Adventure"
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,"Thriller, Action, Crime"
3,Ant-Man,Armed with the astonishing ability to shrink i...,"Science Fiction, Adventure, Action"
4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...","Adventure, Family, Fantasy"
...,...,...,...
9684,Zapped!,Peyton and Barney are fun loving high school s...,"TV Movie, Comedy, Family"
9685,The Good Night,"Gary, a musician, is trapped in an unhappy rel...","Comedy, Drama, Romance, Fantasy, Music"
9686,The World Is Yours,"To escape his life of crime, a Paris drug deal...","Comedy, Crime"
9687,The Grand Seduction,A small fishing village must procure a local d...,Comedy
9688,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...","Adventure, Action, Comedy, Fantasy"

In [17]:
hdf.shape

(9689, 3)

In [18]:
hdf.dropna(subset=['desc'], inplace=True)

In [19]:
htitleFeature = hdf['title']
hdescFeature = hdf['desc']
hgenreFeature = hdf['genre'].str.replace(","," ")
# genreFeature
hdescFeature

0       The near future, a time when both hope and har...
1       After he and his wife are murdered, marine Ray...
2       Marcus and Mike are forced to confront new thr...
3       Armed with the astonishing ability to shrink i...
4       In their quest to confront the ultimate evil, ...
                              ...
9684    Peyton and Barney are fun loving high school s...
9685    Gary, a musician, is trapped in an unhappy rel...
9686    To escape his life of crime, a Paris drug deal...
9687    A small fishing village must procure a local d...
9688    Spanning four centuries in Korea, this epic ac...
Name: desc, Length: 9659, dtype: object

In [20]:
hdescGenreFeature = hgenreFeature.fillna("") + hdescFeature.fillna("")
hdescGenreFeature

0       Science Fiction  DramaThe near future, a time ...
1       Action  Science Fiction  AdventureAfter he and...
2       Thriller  Action  CrimeMarcus and Mike are for...
3       Science Fiction  Adventure  ActionArmed with t...
4       Adventure  Family  FantasyIn their quest to co...
                              ...
9684    TV Movie  Comedy  FamilyPeyton and Barney are ...
9685    Comedy  Drama  Romance  Fantasy  MusicGary, a ...
9686    Comedy  CrimeTo escape his life of crime, a Pa...
9687    ComedyA small fishing village must procure a l...
9688    Adventure  Action  Comedy  FantasySpanning fou...
Length: 9659, dtype: object

In [21]:
print(len(hdescGenreFeature))
print(len(hdf))

9659
9659

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
hvectorizer = TfidfVectorizer(stop_words="english")

hdecvec = hvectorizer.fit_transform(hdescGenreFeature)
print(hvectorizer.get_feature_names_out())

# hsearchDec = "Action based new cool fiction story"
# hsearchDec = "horror"
# hsearchDec = hdf["desc"].iloc[100]
hsearchDec = "serial killer murder investigation"

hsrchDecVec = hvectorizer.transform([hsearchDec])

['00' '000' '006' ... 'žižek' 'βwzvz' '運轉手之戀']

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

hsimilarDec = cosine_similarity(hsrchDecVec,hdecvec).flatten()
print(hsimilarDec)

topK = 5
htopIndexDec = np.argsort(hsimilarDec)[::-1][:topK]
print(htopIndexDec)

[0. 0. 0. ... 0. 0. 0.]
[3996 6312 4874 8121  790]

In [30]:
print("Search keyword: ",hsearchDec)
print("\n")
for i in htopIndexDec:
    print(hdf['title'].iloc[i])
    print("Cosine Value: ", hsimilarDec[i])
    print(hdf['desc'].iloc[i])
    print("\n")

Search keyword:  serial killer murder investigation


Kalifornia
Cosine Value:  0.5590180086970403
A journalist duo go on a tour of serial killer murder sites with two companions, unaware that one of them is a serial killer himself.


Maniac Cop 2
Cosine Value:  0.36096140294653883
A supernatural, maniac killer cop teams up with a Times Square serial killer.


Copycat
Cosine Value:  0.35332114442098306
An agoraphobic psychologist and a female detective must work together to take down a serial killer who copies serial killers from the past.


Replicant
Cosine Value:  0.3444981759730261
Scientists create a genetic clone of a serial killer in order to help catch the killer, teaming up with two cops.


Zodiac
Cosine Value:  0.3224965304437188
The true story of the investigation of the "Zodiac Killer", a serial killer who terrified the San Francisco Bay Area, taunting police with his ciphers and letters. The case becomes an obsession for three men as their lives and careers are built and destroyed by the endless trail of clues.