In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("IMDB_10000.csv")
df

,title,year,certificate,runtime,genre,desc,rating,votes
0,Freddy,2022,UA 16+,124 min,"Drama, Mystery, Thriller",The lines between love and obsession blur in t...,7.9,"16,441"
1,An Action Hero,2022,U,130 min,Action,Youth Icon. Superstar. Action Hero. At the age...,8.1,"15,690"
2,Kantara,2022,UA,148 min,"Action, Adventure, Drama",It involves culture of Kambala and Bhootha Kol...,8.7,"78,358"
3,Khakee: The Bihar Chapter,2022–,UA 13+,45 min,"Action, Crime, Drama",As a righteous cop pursues a merciless crimina...,8.3,"4,464"
4,Drishyam 2,2022,UA,140 min,"Crime, Drama, Mystery",A gripping tale of an investigation and a fami...,8.6,"18,743"
...,...,...,...,...,...,...,...,...
9995,Kisan Aur Bhagwan,1974,NaN,142 min,"Action, Comedy, Drama",NaN,NaN,NaN
9996,Aadmi Sadak Ka,1977,NaN,138 min,"Drama, Family",NaN,NaN,NaN
9997,Nadodi Mannan,1958,NaN,220 min,"Action, Adventure, Comedy",NaN,NaN,NaN
9998,Njan Marykutty,2018,U,126 min,Drama,NaN,NaN,NaN
9999,Paap Ko Jalaa Kar Raakh Kar Doonga,1988,UA,153 min,Crime,NaN,NaN,NaN

In [3]:
df = df.dropna()
df.shape

(5440, 8)

In [4]:
df

,title,year,certificate,runtime,genre,desc,rating,votes
0,Freddy,2022,UA 16+,124 min,"Drama, Mystery, Thriller",The lines between love and obsession blur in t...,7.9,"16,441"
1,An Action Hero,2022,U,130 min,Action,Youth Icon. Superstar. Action Hero. At the age...,8.1,"15,690"
2,Kantara,2022,UA,148 min,"Action, Adventure, Drama",It involves culture of Kambala and Bhootha Kol...,8.7,"78,358"
3,Khakee: The Bihar Chapter,2022–,UA 13+,45 min,"Action, Crime, Drama",As a righteous cop pursues a merciless crimina...,8.3,"4,464"
4,Drishyam 2,2022,UA,140 min,"Crime, Drama, Mystery",A gripping tale of an investigation and a fami...,8.6,"18,743"
...,...,...,...,...,...,...,...,...
8953,Pyaar Kii Ye Ek Kahaani,2010–2021,PG,24 min,"Fantasy, Romance",The story of a young village girl who abandons...,8.4,17
8954,Hero Gayab Mode On,2020–2021,UA 13+,23 min,"Action, Adventure, Fantasy","Ghasitaram, under pressure from his wife, deci...",6.6,23
8955,Aakashavaani,2021,UA 16+,124 min,Drama,The Nath family consists of Retired Commission...,5.5,39
8956,Aladdin - Naam Toh Suna Hoga,2018–2021,U,22 min,Fantasy,A wanderer/revolutionary is a dead ringer for ...,8.1,110
8957,Mr. Majnu,2019,UA,145 min,Romance,A transsexual man's attempt to realize his tru...,7.1,592

In [5]:
features = df.columns.to_list()
print(features)

['title', 'year', 'certificate', 'runtime', 'genre', 'desc', 'rating', 'votes']

In [14]:
titleFeature = df['title']
descFeature = df['desc']
genreFeature = df['genre'].str.replace(","," ")
# genreFeature
descFeature

0       The lines between love and obsession blur in t...
1       Youth Icon. Superstar. Action Hero. At the age...
2       It involves culture of Kambala and Bhootha Kol...
3       As a righteous cop pursues a merciless crimina...
4       A gripping tale of an investigation and a fami...
                              ...
8953    The story of a young village girl who abandons...
8954    Ghasitaram, under pressure from his wife, deci...
8955    The Nath family consists of Retired Commission...
8956    A wanderer/revolutionary is a dead ringer for ...
8957    A transsexual man's attempt to realize his tru...
Name: desc, Length: 5440, dtype: object

In [7]:
uniqueFeatures = ['year','certificate','genre']
genre = []
for i in uniqueFeatures:
    if i=='genre':
        genre = df[i].unique()
    print(i)
    print(df[i].unique())
    print("\n")

year
['2022' '2022–' 'I 2022' '2016' '2019' '2018–' '2018' '2011' '2008' '2009'
 '2015' 'III 2022' '2017' '2020' '2020–' '2021' '2012' '2019–2022' '2019–'
 '2021–' '2004' 'I 2006' 'I 2017' '1982' '2014' '2007' '2011–2018'
 '2018–2019' '2019–2021' '2015–2022' '2023' 'I 2010' 'V 2022' 'II 2022'
 'I 2016' 'I 2021' '2016–' '2006' 'I 2018' '2015–' '2001' '2013' '2003'
 '1998' '2010' '2006–' '1955' 'I 2002' '1995' 'III 2018' 'I 2020' 'I 2013'
 '2017–' 'II 2020' '1959' '2020–2022' '2014–' '2000–2008' 'III 2016'
 '1991' '2016–2019' '2002' '2000' '2016–2017' 'II 2018' 'I 2020–'
 '2013–2016' '2013–2014' '1993' '1975' 'XVII 2016' '2005' '1994' '1957'
 'II 2019' '2004–' '2009–' 'I 2014' '1988–1990' 'I 2019' '2011–2014'
 '1997' '1987–1988' '2016–2021' '2003–2007' 'I 2011' '2008–' 'III 2021'
 'VI 2020' 'I 2015' '2011–2016' '1999' '2019–2020' '1956' '2004–2017'
 '2013–2015' '1988' '1987' '2014–2015' 'III 2019' '2011–2013' '2009–2011'
 '2003–2004' '1963' '2013–2019' '2005–2007' '1998–2018' '2008 Video'
 '2003–2006' 'I 2009' '1989' 'I 1964' '2008–2009' '1973' 'I 2003' '1977'
 '1990–' 'III 2017' '1992' '1983' '1996' '1966' 'I 2007' 'VII 2015'
 '2020–2021' '1964' 'V 2019' 'I 2005' '1971' '1978' '1968' '2018–2020'
 '2013–' '2012–2013' '2009–2014' 'IV 2020' '2000–2002' '1965' '2016–2018'
 '2014–2022' '2012–2016' '2005–2011' 'II 1983' 'II 2012' '1981' 'II 2021'
 'I 1989' '1972' '1984–1985' '2002–' '1967' '1990' '1980' '2012–2014'
 '1979' '2017–2019' '1970' '2008 TV Movie' 'IV 2017' 'III 2013'
 '2009–2012' '1974' '1984' 'II 1998' 'VIII 2019' '2011 TV Movie' '1969'
 '2015–2016' '2006–2009' '2017–2018' '1953' '1986' '2015–2019' '1958'
 'I 2021–' '1985' 'I 2008' '2014–2016' '1993–1997' 'II 2017' '2015–2017'
 '2010–' 'VII 2018' '2005–2010' 'I 1986' 'II 2019–' '2007–2010' 'I 2012'
 'IV 2022' '1976' 'III 2015' '1951' '1960' 'II 2013' '2018–2021'
 '2021–2022' '1988–1989' 'IV 2016' '2018–2022' '2022 TV Special'
 '2014–2019' '1954' 'I 1965' 'II 1994' '1997–2005' '2001–2007' '2008–2010'
 'I 2001' '1952' 'I 1996' '1994–' 'I 1983' 'II 2014' '2000–2004'
 'III 2020' '2002–2009' '2010–2017' '2000–' '1961' 'II 2014–' '2010–2016'
 'V 2015' '1995–2006' 'II 2016' '2012 Video' 'II 1995–2015' '2009–2019'
 '2008–2016' '2005–' '2009–2010' 'II 2010' '2010–2011' 'II' 'VI 2015'
 '2021 Video' 'I 1980' '2014 Video' '1962' 'II 2011' '2012–2018' '1949'
 '2017–2020' 'I 1999' 'II 2020–2021' 'IV 2019' 'II 1976' '2017–2021'
 'VII 2021' 'II 2004' 'II 2021–' '2023–' '2014–2017' '2001–2004' '1996–'
 '2001–2008' '1938' '2000–2003' '2016 TV Movie' '1946' '2011–2012'
 '2010–2021']


certificate
['UA 16+' 'U' 'UA' 'UA 13+' 'R' 'A' '16+' '18' 'Not Rated' '16' '15+'
 '18+' 'PG' '13' '12+' 'PG-13' 'Unrated' 'UA 7+' 'U/A' '7' '(Banned)' '15'
 'All' '7+' 'G' '13+']


genre
['Drama, Mystery, Thriller            ' 'Action            '
 'Action, Adventure, Drama            ' 'Action, Crime, Drama            '
 'Crime, Drama, Mystery            ' 'Drama, History, Music            '
 'Comedy, Horror, Thriller            '
 'Comedy, Drama, Family            ' 'Action, Drama            '
 'Drama            ' 'Comedy            '
 'Drama, Romance, Thriller            '
 'Action, Drama, Mystery            '
 'Action, Adventure, Fantasy            ' 'Action, Drama, War            '
 'Comedy, Drama, Romance            ' 'Comedy, Crime, Drama            '
 'Action, Adventure, Sci-Fi            ' 'Drama, Thriller            '
 'Action, Drama, Family            '
 'Action, Sci-Fi, Thriller            '
 'Adventure, Biography, Drama            ' 'Crime, Thriller            '
 'Action, Adventure            ' 'Adventure, Drama, Sci-Fi            '
 'Comedy, Drama            ' 'Drama, History, Thriller            '
 'Action, Adventure, Crime            '
 'Drama, Horror, Mystery            ' 'Drama, Fantasy, Horror            '
 'Action, Crime, Sci-Fi            ' 'Horror, Thriller            '
 'Adventure, Drama, Fantasy            '
 'Biography, Drama, History            '
 'Action, Drama, Romance            ' 'Biography, Drama            '
 'Adventure, Drama            ' 'Action, Mystery, Thriller            '
 'Action, Comedy, Drama            ' 'Animation            '
 'Comedy, Fantasy            ' 'Biography, Crime, Drama            '
 'Action, Drama, Thriller            ' 'Action, Thriller            '
 'Crime, Drama, Thriller            ' 'Action, Drama, Sci-Fi            '
 'Adventure, Family, Fantasy            ' 'Romance            '
 'Adventure, Comedy, Drama            ' 'Comedy, Horror            '
 'Drama, Romance            ' 'Crime, Mystery, Thriller            '
 'Action, Biography, Drama            '
 'Action, Crime, Thriller            '
 'Adventure, Drama, History            ' 'Crime, Drama            '
 'Action, Drama, Sport            ' 'Crime            '
 'Comedy, Drama, Thriller            '
 'Drama, Fantasy, Mystery            ' 'Comedy, Drama, Sci-Fi            '
 'Comedy, Family, Fantasy            ' 'Comedy, Crime, Music            '
 'Action, Drama, History            '
 'Action, Romance, Thriller            '
 'Action, Comedy, Crime            ' 'Comedy, Drama, Musical            '
 'Drama, Family            ' 'Drama, Musical, Romance            '
 'Adventure, Drama, Romance            ' 'Reality-TV            '
 'Action, Drama, Fantasy            '
 'Documentary, Crime, History            ' 'Drama, Musical            '
 'Drama, Sport            ' 'Drama, Musical, Sport            '
 'Action, Crime, Romance            ' 'Comedy, Crime, Mystery            '
 'Comedy, Romance            ' 'Drama, Music, Romance            '
 'Documentary, Crime            ' 'Biography            '
 'Action, Horror, Thriller            '
 'Drama, History, Romance            ' 'Comedy, Drama, Horror            '
 'Thriller            ' 'Documentary, Sport            '
 'Comedy, Drama, Fantasy            '
 'Biography, Comedy, Drama            '
 'Biography, Drama, Sport            '
 'Action, Adventure, Comedy            '
 'Drama, Music, Musical            ' 'Drama, Family, Musical            '
 'Action, Crime            ' 'Animation, Adventure, Comedy            '
 'Biography, Drama, War            ' 'Comedy, Drama, Music            '
 'Short            ' 'Action, Comedy            '
 'Drama, Family, Romance            '
 'Action, Comedy, Thriller            '
 'Musical, Drama, Romance            '
 'Action, Adventure, Thriller            ' 'Drama, History            '
 'Drama, Family, Sport            ' 'Drama, History, War            '
 'Action, Biography, Crime            '
 'Crime, Drama, Musical            ' 'Action, Comedy, Romance            '
 'Drama, Horror, Thriller            ' 'Crime, Drama, Romance            '
 'Biography, Crime, Thriller            ' 'Mystery, Thriller            '
 'Comedy, Talk-Show            ' 'Action, Musical, Romance            '
 'Comedy, Crime            '
 'Documentary, Reality-TV, Romance            '
 'Animation, Action, Adventure            ' 'Drama, Music            '
 'Comedy, Crime, Romance            ' 'Mystery            '
 'Adventure, Drama, Family            '
 'Action, Drama, Musical            '
 'Adventure, Drama, Thriller            '
 'Action, Adventure, Romance            ' 'Comedy, Family            '
 'Drama, Horror, Romance            ' 'Drama, Mystery            '
 'Crime, Drama, Horror            ' 'Action, Comedy, Fantasy            '
 'Drama, Horror            ' 'Horror            ' 'Fantasy            '
 'Drama, Sci-Fi, Thriller            '
 'Horror, Mystery, Thriller            '
 'Comedy, Drama, Mystery            ' 'Drama, War            '
 'Drama, Mystery, Romance            '
 'Drama, Fantasy, Romance            '
 'Comedy, Horror, Mystery            '
 'Animation, Adventure, Family            ' 'Drama, Sci-Fi            '
 'Action, Fantasy, Horror            '
 'Comedy, Fantasy, Romance            ' 'Comedy, Drama, Sport            '
 'Family, Romance            ' 'Action, Crime, Mystery            '
 'Action, Comedy, Horror            ' 'Comedy, Thriller            '
 'Comedy, Drama, History            ' 'Crime, Horror, Mystery            '
 'Horror, Romance, Thriller            '
 'Action, Musical, Mystery            '
 'Horror, Mystery, Romance            '
 'Biography, Drama, Music            '
 'Crime, Romance, Thriller            ' 'Horror, Mystery            '
 'History            ' 'Drama, History, Sport            '
 'Drama, Fantasy            ' 'Action, Horror, Sci-Fi            '
 'Crime, Drama, History            '
 'Comedy, Musical, Romance            '
 'Crime, Horror, Romance            ' 'Family            '
 'Mystery, Romance, Thriller            '
 'Animation, Comedy, Family            ' 'Documentary            '
 'Documentary, Biography, Crime            '
 'Documentary, Romance            ' 'Crime, Mystery, Romance            '
 'Action, Romance            ' 'Comedy, Sci-Fi, Thriller            '
 'Crime, Drama, Fantasy            ' 'Action, Comedy, Musical            '
 'Biography, Drama, Thriller            '
 'Animation, Drama, Romance            '
 'Crime, History, Thriller            '
 'Adventure, Horror, Mystery            '
 'Adventure, Family, Musical            '
 'Action, Comedy, Family            ' 'Comedy, Musical, Drama            '
 'Adventure, Drama, Mystery            '
 'Comedy, Crime, Thriller            '
 'Drama, Thriller, Action            ' 'Fantasy, Thriller            '
 'Action, Crime, Musical            '
 'Musical, Romance, Drama            '
 'Biography, Drama, Romance            '
 'Biography, History, Mystery            ' 'Romance, Drama            '
 'Action, Biography, History            ' 'Adventure, Fantasy            '
 'Drama, Family, Fantasy            ' 'Action, Thriller, War            '
 'Comedy, Mystery, Thriller            '
 'Drama, Horror, Musical            '
 'Animation, Adventure, Fantasy            '
 'Drama, Action, Musical            '
 'Crime, Musical, Mystery            '
 'Animation, Short, Adventure            '
 'Family, Musical, Romance            '
 'Fantasy, Horror, Mystery            '
 'Comedy, Family, Sci-Fi            ' 'Animation, Drama            '
 'Adventure, Comedy, Family            '
 'Drama, Fantasy, Thriller            '
 'Fantasy, Mystery, Romance            '
 'Fantasy, Mystery, Sci-Fi            '
 'Documentary, Thriller            ' 'Action, Comedy, War            '
 'Adventure, Comedy, Crime            ' 'Short, Drama            '
 'Romance, Thriller            ' 'Adventure, Crime, Mystery            '
 'News            ' 'Musical, Romance            '
 'Action, Adventure, Horror            ' 'Crime, Mystery            '
 'Drama, Family, Music            ' 'Short, Romance            '
 'Musical            ' 'Adventure, Comedy, Horror            '
 'Fantasy, Romance            ' 'Game-Show            '
 'Musical, Fantasy            ' 'Comedy, Fantasy, Horror            '
 'Musical, Mystery, Thriller            '
 'Fantasy, Musical, Mystery            '
 'Adventure, Mystery, Thriller            '
 'Action, Adventure, Family            '
 'Action, Adventure, Mystery            '
 'Adventure, Horror, Romance            '
 'Crime, Sci-Fi, Thriller            '
 'Fantasy, Horror, Romance            '
 'Comedy, Family, Romance            ' 'Action, Drama, Horror            '
 'Drama, Romance, War            ' 'Adventure, Comedy            '
 'Sport            ' 'Comedy, History            '
 'Comedy, Musical            ' 'Adventure, Romance            '
 'History, War            ' 'Comedy, Romance, Sci-Fi            '
 'Comedy, Drama, War            ' 'Action, Sport            '
 'Drama, Romance, Musical            ' 'Sci-Fi, Thriller            '
 'Fantasy, Horror            ' 'Action, Adventure, Biography            '
 'Action, Mystery, Romance            '
 'Drama, Fantasy, Musical            '
 'Adventure, Comedy, Sci-Fi            '
 'Adventure, Family, Mystery            '
 'Action, Crime, History            '
 'Action, Thriller, Crime            '
 'Action, Fantasy, Thriller            '
 'Animation, Adventure, History            ' 'Sci-Fi            '
 'Crime, Drama, Music            ' 'Adventure, Drama, Musical            '
 'Comedy, Romance, Thriller            '
 'Comedy, Music, Romance            ' 'Comedy, Romance, Drama            '
 'Comedy, Romance, Sport            ' 'Comedy, Mystery            '
 'Drama, Adventure, Action            ' 'Romance, Sci-Fi            '
 'Action, Crime, Horror            ' 'Short, Comedy, Thriller            '
 'Drama, Family, Thriller            ' 'Comedy, Sport            '
 'Drama, Family, Comedy            ' 'Short, Horror            '
 'Drama, Musical, Thriller            '
 'Biography, Drama, Family            '
 'Action, Romance, Sci-Fi            '
 'Action, Fantasy, Musical            '
 'Fantasy, Horror, Sci-Fi            ' 'Biography, Comedy            '
 'Romance, Comedy, Drama            ' 'Thriller, Mystery            '
 'Romance, Musical, Drama            '
 'Documentary, Talk-Show            ' 'Musical, Drama, Comedy            '
 'Adventure, Horror, Thriller            '
 'Musical, Reality-TV            ' 'Action, Drama, Crime            '
 'Documentary, Drama            ' 'Comedy, Romance, Musical            '
 'Action, Family            ' 'Short, Romance, Thriller            '
 'Drama, Musical, Family            ' 'Action, Drama, Music            '
 'Drama, Fantasy, History            '
 'Romance, Action, Crime            '
 'Action, Fantasy, Romance            '
 'Drama, Sport, Thriller            ' 'Action, Biography            '
 'Family, Musical            ' 'War            '
 'Action, Musical, War            '
 'Musical, Romance, Thriller            ' 'Action, Fantasy            '
 'Drama, Music, Mystery            '
 'Documentary, Crime, Mystery            '
 'Drama, Family, History            ' 'Crime, Game-Show            '
 'Animation, Fantasy            ' 'Action, Family, Romance            '
 'Action, Romance, Comedy            ' 'Family, Thriller            '
 'Action, War            ' 'Biography, Drama, Fantasy            '
 'Horror, Sci-Fi, Thriller            '
 'Documentary, Drama, Sport            '
 'Action, Drama, Western            ' 'Horror, Drama, Mystery            '
 'Animation, Family            ' 'Adventure            '
 'Biography, Fantasy            ' 'Musical, Thriller            '
 'Action, History            ' 'Crime, Horror, Thriller            '
 'Adventure, Thriller            '
 'Documentary, Drama, Thriller            '
 'Adventure, Comedy, Fantasy            '
 'Comedy, Musical, Action            '
 'Crime, Musical, Romance            '
 'Crime, Fantasy, Romance            '
 'Adventure, Crime, Family            ' 'Short, Action, Drama            '
 'Comedy, Sport, Thriller            '
 'Drama, History, Musical            ' 'Short, Drama, Romance            '
 'Short, Crime, Drama            ' 'Musical, Mystery, Drama            '
 'Reality-TV, Romance            ' 'Comedy, Mystery, Romance            '
 'Comedy, Horror, Romance            '
 'Short, Sci-Fi, Thriller            ' 'History, News            '
 'Family, Drama            ' 'Romance, Musical, Comedy            '
 'Musical, Drama, Crime            '
 'Mystery, Romance, Musical            ' 'Documentary, Family            '
 'Drama, Musical, Mystery            '
 'Fantasy, Horror, Thriller            '
 'Comedy, Family, History            '
 'Musical, Thriller, Mystery            '
 'Drama, Family, Horror            ' 'Documentary, History            '
 'Musical, Drama            ' 'Musical, Comedy, Romance            '
 'Short, Adventure            ' 'Adventure, Romance, Thriller            '
 'Comedy, Family, Musical            ' 'Biography, History            '
 'Horror, Romance, Sci-Fi            ']

#### Genre based Only

In [8]:
# genre = genre.tolist()
# print(genre)
uniqueGenre = set()
for i in genre:
    Glist = i.split(",")
    for j in Glist:
        if j[0]==" " or j[len(j)-1]==" ":
            removeSpace = j.split(" ")
            for u in removeSpace:
                if u!=" ":
                    uniqueGenre.add(u)
        else:
            uniqueGenre.add(j)
print(uniqueGenre)
print(len(uniqueGenre))

{'', 'Horror', 'Game-Show', 'Crime', 'Animation', 'Comedy', 'History', 'Talk-Show', 'Musical', 'Romance', 'Short', 'Sci-Fi', 'Drama', 'Western', 'Fantasy', 'News', 'Biography', 'Documentary', 'Sport', 'Music', 'Mystery', 'Adventure', 'Action', 'Reality-TV', 'War', 'Family', 'Thriller'}
27

In [9]:
# k = " Drama            "
# k= "Family            "
# if j[0]==" " or j[len(j)-1]==" ":
#         removeSpace = k.split(" ")
#         for u in removeSpace:
#             if u!=" ":
#                   uniqueGenre.add(j)
#         print(removeSpace)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

vec = vectorizer.fit_transform(genreFeature)
print(vectorizer.get_feature_names_out())

search = "drama thriller"
srchVec = vectorizer.transform([search])

# print(vec.toarray())

['action' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'fi' 'game' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality' 'romance' 'sci' 'short'
 'show' 'sport' 'talk' 'thriller' 'tv' 'war' 'western']
['action' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'fi' 'game' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality' 'romance' 'sci' 'short'
 'show' 'sport' 'talk' 'thriller' 'tv' 'war' 'western']

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

similar = cosine_similarity(srchVec,vec).flatten()
print(similar)

topK = 5
topIndex = np.argsort(similar)[::-1][:topK]
print(topIndex)

[0.81649658 0.         0.40824829 ... 0.70710678 0.         0.        ]
[ 419   22 1433 3098 3112]

In [12]:
for i in topIndex:
    print(df['title'].iloc[i])
    print("Cosine Value: ", similar[i])
    print("\n")

Trapped
Cosine Value:  0.9999999999999998


Blurr
Cosine Value:  0.9999999999999998


Malayankunju
Cosine Value:  0.9999999999999998


Meppadiyan
Cosine Value:  0.9999999999999998


Maalgudi Days
Cosine Value:  0.9999999999999998

#### Desc based Only

In [15]:
descFeature

0       The lines between love and obsession blur in t...
1       Youth Icon. Superstar. Action Hero. At the age...
2       It involves culture of Kambala and Bhootha Kol...
3       As a righteous cop pursues a merciless crimina...
4       A gripping tale of an investigation and a fami...
                              ...
8953    The story of a young village girl who abandons...
8954    Ghasitaram, under pressure from his wife, deci...
8955    The Nath family consists of Retired Commission...
8956    A wanderer/revolutionary is a dead ringer for ...
8957    A transsexual man's attempt to realize his tru...
Name: desc, Length: 5440, dtype: object

In [29]:
vectorizer = CountVectorizer()

decvec = vectorizer.fit_transform(descFeature)
print(vectorizer.get_feature_names_out())

# searchDec = "Action based new cool fiction story"
searchDec = "horror"
srchDecVec = vectorizer.transform([searchDec])

# print(vec.toarray())

['000' '10' '100' ... 'zuhu' 'zumba' 'zwigato']

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

similarDec = cosine_similarity(srchDecVec,decvec).flatten()
print(similarDec)

topK = 5
topIndexDec = np.argsort(similarDec)[::-1][:topK]
print(topIndexDec)

[0. 0. 0. ... 0. 0. 0.]
[1820 3169 3064  940  943]

In [ ]:
for i in topIndexDec:
    print(df['title'].iloc[i])
    print("Cosine Value: ", similarDec[i])
    print(df['desc'].iloc[i])
    print("\n")